#!/usr/bin/env python3
# 第二题

import sys


def expr_func(args: list):
    index = 0
    while True:
        if '+' in args or '-' in args or '*' in args or '/' in args:
            if args[index] in list('+-*/'):
                if index < 2:
                    raise ValueError("错误的逆波兰表达式")

                sign = args.pop(index)
                try:
                    num2 = int(args.pop(index - 1))
                    num_1 = int(args[index - 2])
                except Exception as e:
                    raise ValueError("错误的逆波兰表达式")

                if sign == "+":
                    args[index - 2] = num_1 + num2
                elif sign == "-":
                    args[index - 2] = num_1 - num2
                elif sign == '*':
                    args[index - 2] = num_1 * num2
                elif sign == '/':
                    args[index - 2] = num_1 / num2
                else:
                    raise ValueError(f"不支持的操作符{args[index]}")

                index = 0
            else:
                index = index + 1
        else:
            break

    if len(args) > 1:
        raise ValueError("错误的波兰表达式")
    return args[0]


if __name__ == "__main__":
    print("第二题")
    args_ = sys.argv[1:]
    print(f"args is{args_}")
    print(expr_func(list(args_[0])))
